### ISSUE TITLE
Tasks list

### ISSUE THREAD

**Issue by Milesq** [Milesq/survey#1]

**Comment by alexszolowicz-blockether** [comment]
- input for first & last name
- code for joining the test
- connection to the local database
- questions and answers in random order
- safe api
- anti-cheat

**Comment by ewagriusz** [comment]
- remove the option to change the answer

**Comment by Milesq** [comment]
![unknown](https://user-images.githubusercontent.com/29902079/107626475-22b5d680-6c5e-11eb-9b71-e73291764bbc.png)
